Repository MoaRoom/MoaRoom-Back, pull requests merged in 2023-08, with the labels that each got.

#61 순환참조 오류 해결
  src/main/java/sookmyung/moaroom/Service/StepService.java
  src/main/java/sookmyung/moaroom/Service/TimerScheduler.java
Labels: Fix

#64 API URL 리팩토링
  src/main/java/sookmyung/moaroom/Controller/AssignmentController.java
  src/main/java/sookmyung/moaroom/Controller/LectureController.java
  src/main/java/sookmyung/moaroom/Controller/StepController.java
  src/main/java/sookmyung/moaroom/Controller/UserController.java
  src/main/java/sookmyung/moaroom/Dto/requestAssignmentDto.java
  src/main/java/sookmyung/moaroom/Dto/requestEnrollDto.java
  src/main/java/sookmyung/moaroom/Dto/requestLectureDto.java
  src/main/java/sookmyung/moaroom/Dto/requestScoreDto.java
  src/main/java/sookmyung/moaroom/Dto/requestUserDto.java
  src/main/java/sookmyung/moaroom/Service/AssignmentService.java
  src/main/java/sookmyung/moaroom/Service/EnrollService.java
  src/main/java/sookmyung/moaroom/Service/LectureService.java
  src/main/java/sookmyung/moaroom/Service/StepService.java
  src/main/java/sookmyung/moaroom/Service/UserService.java
  src/main/resources/API/FrontEnd/Assignment.md
  src/main/resources/API/FrontEnd/Lecture.md
  src/main/resources/API/FrontEnd/Step.md
  src/main/resources/API/FrontEnd/User.md
  src/main/resources/API/Infra/URL.md
Labels: Refactor

#79 Cors 추가-Front localhost
  src/main/java/sookmyung/moaroom/MoaroomApplication.java
Labels: Fix, Add

#82 hotfix cors adding from multi-str to single-list
  src/main/java/sookmyung/moaroom/MoaroomApplication.java
Labels: Fix

#85 infra URL 수정
  src/main/java/sookmyung/moaroom/MoaroomApplication.java
  src/main/java/sookmyung/moaroom/Service/EnrollService.java
  src/main/java/sookmyung/moaroom/Service/UserService.java
Labels: Fix

#87 dependency 추가
  build.gradle
  src/main/java/sookmyung/moaroom/Controller/StepController.java
Labels: Fix

#89 과제 dto에 실행시간, 답안 추가
  src/main/java/sookmyung/moaroom/Dto/requestAssignmentDto.java
  src/main/java/sookmyung/moaroom/Model/Assignment.java
  src/main/java/sookmyung/moaroom/Service/AssignmentService.java
Labels: Add

#92 url dto 수정
  src/main/java/sookmyung/moaroom/Controller/AssignmentController.java
  src/main/java/sookmyung/moaroom/Controller/UserController.java
  src/main/java/sookmyung/moaroom/Model/Url.java
  src/main/java/sookmyung/moaroom/Respository/UrlRepository.java
  src/main/java/sookmyung/moaroom/Service/EnrollService.java
  src/main/java/sookmyung/moaroom/Service/UserService.java
  src/main/resources/API/Infra/URL.md
Labels: Fix, Refactor

#93 자동 채점
  src/main/java/sookmyung/moaroom/Controller/StepController.java
  src/main/java/sookmyung/moaroom/Dto/requestAutoScoreDto.java
  src/main/java/sookmyung/moaroom/Respository/StepRepository.java
  src/main/java/sookmyung/moaroom/Service/AssignmentService.java
  src/main/java/sookmyung/moaroom/Service/StepService.java
Labels: Add
